export const TRANSLATIONS = {
  en: {
    title: 'NutriTrack',
    subtitle: 'Track your habits, nourish your life',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snack: 'Snacks',
    water: 'Water Intake',
    waterUnit: 'ml',
    addMeal: 'Add Meal',
    mealPlaceholder: 'What did you eat?',
    save: 'Save',
    todaySummary: "Today's Summary",
    aiAnalysis: 'AI Health Rating',
    analyzeBtn: 'Analyze Habits',
    rating: 'Rating',
    feedbackTitle: 'AI Feedback',
    suggestionsTitle: 'Suggestions',
    noData: 'Log your meals to get an analysis!',
    analyzing: 'Analyzing your habits...',
    switchLang: '中文',
    history: 'History',
    clearHistory: 'Clear Data',
    waterGoal: 'Daily Goal: 2000ml',
    healthyHabit: 'Healthy Habits',
    notYetHealthy: 'Not Yet Healthy',
  },
  zh: {
    title: '營養追蹤 (NutriTrack)',
    subtitle: '記錄你的飲食習慣，滋養你的生活',
    breakfast: '早餐',
    lunch: '午餐',
    dinner: '晚餐',
    snack: '零食/點心',
    water: '飲水量',
    waterUnit: '毫升',
    addMeal: '記錄餐點',
    mealPlaceholder: '你吃了什麼？',
    save: '儲存',
    todaySummary: '今日摘要',
    aiAnalysis: 'AI 健康評分',
    analyzeBtn: '分析飲食習慣',
    rating: '評分',
    feedbackTitle: 'AI 回饋',
    suggestionsTitle: '改善建議',
    noData: '請記錄你的餐點以獲取分析！',
    analyzing: '正在分析你的飲食習慣...',
    switchLang: 'English',
    history: '歷史記錄',
    clearHistory: '清除數據',
    waterGoal: '每日目標：2000毫升',
    healthyHabit: '健康的習慣',
    notYetHealthy: '尚未健康',
  },
};

export type Language = 'en' | 'zh';
