export const TRANSLATIONS = {
  en: {
    title: 'Hanigo',
    subtitle: 'Your personal AI travel advisor',
    city: 'City',
    country: 'Country',
    duration: 'Duration (Days)',
    cityPlaceholder: 'e.g., Paris',
    countryPlaceholder: 'e.g., France',
    durationPlaceholder: 'How many days?',
    getAdvice: 'Get Travel Advice',
    loading: 'Consulting local experts...',
    placesTitle: 'Famous Places to Visit',
    foodTitle: 'Must-Try Local Food',
    adviceFor: 'Advice for',
    daysIn: 'days in',
    newSearch: 'New Search',
    switchLang: '中文',
    clearHistory: 'Clear History',
    history: 'Recent Searches',
    error: 'Could not get advice. Please try again.',
  },
  zh: {
    title: 'Hanigo (旅行者)',
    subtitle: '您的專屬 AI 旅遊顧問',
    city: '城市',
    country: '國家',
    duration: '停留天數',
    cityPlaceholder: '例如：巴黎',
    countryPlaceholder: '例如：法國',
    durationPlaceholder: '停留幾天？',
    getAdvice: '獲取旅遊建議',
    loading: '正在諮詢當地專家...',
    placesTitle: '熱門必訪景點',
    foodTitle: '在地必吃美食',
    adviceFor: '旅遊建議：',
    daysIn: '天停留於',
    newSearch: '重新搜索',
    switchLang: 'English',
    clearHistory: '清除歷史紀錄',
    history: '最近搜尋',
    error: '無法獲取建議，請重試。',
  },
};

export type Language = 'en' | 'zh';
